// Default template for first-time users (FTUX)
// A polished receipt template with common dynamic fields

export const defaultTemplate = {
  title: 'Default Receipt Template',
  background: '#ffffff',
  elements: [
    {
      id: 'el_logo',
      type: 'text',
      x: 540,
      y: 40,
      width: 200,
      height: 60,
      rotation: 0,
      zIndex: 1,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'STORE NAME',
        fontSize: 36,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 700,
        color: '#000000',
        textAlign: 'center',
        lineHeight: 1.2,
      },
    },
    {
      id: 'el_address',
      type: 'text',
      x: 540,
      y: 100,
      width: 200,
      height: 40,
      rotation: 0,
      zIndex: 2,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: '123 Main Street',
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 400,
        color: '#666666',
        textAlign: 'center',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_date_label',
      type: 'text',
      x: 80,
      y: 160,
      width: 120,
      height: 30,
      rotation: 0,
      zIndex: 3,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'Date:',
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 500,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_date',
      type: 'text',
      x: 200,
      y: 160,
      width: 200,
      height: 30,
      rotation: 0,
      zIndex: 4,
      isDynamic: true,
      formFieldType: 'transaction_date',
      placeholderText: '{{transaction_date}}',
      props: {
        text: '2024-01-15',
        fontSize: 14,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_customer_label',
      type: 'text',
      x: 80,
      y: 190,
      width: 120,
      height: 30,
      rotation: 0,
      zIndex: 5,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'Customer:',
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 500,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_customer',
      type: 'text',
      x: 200,
      y: 190,
      width: 300,
      height: 30,
      rotation: 0,
      zIndex: 6,
      isDynamic: true,
      formFieldType: 'customer_name',
      placeholderText: '{{customer_name}}',
      props: {
        text: 'John Doe',
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_items_header',
      type: 'text',
      x: 80,
      y: 240,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 7,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'ITEM',
        fontSize: 12,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 600,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_qty_header',
      type: 'text',
      x: 300,
      y: 240,
      width: 80,
      height: 30,
      rotation: 0,
      zIndex: 8,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'QTY',
        fontSize: 12,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 600,
        color: '#000000',
        textAlign: 'center',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_price_header',
      type: 'text',
      x: 450,
      y: 240,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 9,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'PRICE',
        fontSize: 12,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 600,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_item1',
      type: 'text',
      x: 80,
      y: 270,
      width: 200,
      height: 30,
      rotation: 0,
      zIndex: 10,
      isDynamic: true,
      formFieldType: 'custom_field',
      placeholderText: '{{item_1}}',
      props: {
        text: 'Product A',
        fontSize: 13,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_qty1',
      type: 'text',
      x: 300,
      y: 270,
      width: 80,
      height: 30,
      rotation: 0,
      zIndex: 11,
      isDynamic: true,
      formFieldType: 'custom_field',
      placeholderText: '{{qty_1}}',
      props: {
        text: '2',
        fontSize: 13,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'center',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_price1',
      type: 'text',
      x: 450,
      y: 270,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 12,
      isDynamic: true,
      formFieldType: 'custom_field',
      placeholderText: '{{price_1}}',
      props: {
        text: '$29.99',
        fontSize: 13,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_item2',
      type: 'text',
      x: 80,
      y: 300,
      width: 200,
      height: 30,
      rotation: 0,
      zIndex: 13,
      isDynamic: true,
      formFieldType: 'custom_field',
      placeholderText: '{{item_2}}',
      props: {
        text: 'Product B',
        fontSize: 13,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_qty2',
      type: 'text',
      x: 300,
      y: 300,
      width: 80,
      height: 30,
      rotation: 0,
      zIndex: 14,
      isDynamic: true,
      formFieldType: 'custom_field',
      placeholderText: '{{qty_2}}',
      props: {
        text: '1',
        fontSize: 13,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'center',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_price2',
      type: 'text',
      x: 450,
      y: 300,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 15,
      isDynamic: true,
      formFieldType: 'custom_field',
      placeholderText: '{{price_2}}',
      props: {
        text: '$49.99',
        fontSize: 13,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 400,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_divider',
      type: 'shape',
      x: 80,
      y: 340,
      width: 470,
      height: 2,
      rotation: 0,
      zIndex: 16,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        shape: 'rect',
        fill: '#e0e0e0',
        stroke: 'transparent',
        strokeWidth: 0,
        radius: 0,
      },
    },
    {
      id: 'el_subtotal_label',
      type: 'text',
      x: 350,
      y: 360,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 17,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'Subtotal:',
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 500,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_subtotal',
      type: 'text',
      x: 450,
      y: 360,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 18,
      isDynamic: true,
      formFieldType: 'subtotal',
      placeholderText: '{{subtotal}}',
      props: {
        text: '$79.98',
        fontSize: 14,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 600,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_tax_label',
      type: 'text',
      x: 350,
      y: 390,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 19,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'Tax:',
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 500,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_tax',
      type: 'text',
      x: 450,
      y: 390,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 20,
      isDynamic: true,
      formFieldType: 'tax',
      placeholderText: '{{tax}}',
      props: {
        text: '$6.40',
        fontSize: 14,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 600,
        color: '#000000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_total_label',
      type: 'text',
      x: 350,
      y: 420,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 21,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        text: 'TOTAL:',
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        fontWeight: 700,
        color: '#ff0000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_total',
      type: 'text',
      x: 450,
      y: 420,
      width: 100,
      height: 30,
      rotation: 0,
      zIndex: 22,
      isDynamic: true,
      formFieldType: 'total',
      placeholderText: '{{total}}',
      props: {
        text: '$86.38',
        fontSize: 16,
        fontFamily: 'JetBrains Mono, monospace',
        fontWeight: 700,
        color: '#ff0000',
        textAlign: 'right',
        lineHeight: 1.4,
      },
    },
    {
      id: 'el_barcode',
      type: 'barcode',
      x: 540,
      y: 500,
      width: 240,
      height: 100,
      rotation: 0,
      zIndex: 23,
      isDynamic: false,
      formFieldType: null,
      placeholderText: null,
      props: {
        format: 'CODE128',
        value: '123456789',
        color: '#000000',
      },
    },
  ],
};
