export const TEMPLATES = [
  {
    id: 'classic-market',
    title: 'Classic Market Receipt',
    thumbnail_placeholder: 'Classic Market',
    background: '#ffffff',
    elements: [
      {
        id: 'market-title',
        type: 'text',
        x: 80,
        y: 40,
        width: 560,
        height: 60,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'MARKET SOCIETY',
          fontSize: 40,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.1,
        },
      },
      {
        id: 'market-subtitle',
        type: 'text',
        x: 80,
        y: 100,
        width: 520,
        height: 36,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Vintage goods & fresh staples',
          fontSize: 18,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'market-divider',
        type: 'line',
        x: 80,
        y: 156,
        width: 560,
        height: 2,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          stroke: '#000000',
          strokeWidth: 2,
          strokeStyle: 'solid',
        },
      },
      {
        id: 'market-customer',
        type: 'text',
        x: 80,
        y: 180,
        width: 520,
        height: 45,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'customer_name',
        placeholderText: '{{customer_name}}',
        props: {
          text: 'Customer: {{customer_name}}',
          fontSize: 18,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 500,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
      {
        id: 'market-date',
        type: 'text',
        x: 80,
        y: 230,
        width: 520,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'transaction_date',
        placeholderText: '{{transaction_date}}',
        props: {
          text: 'Date: {{transaction_date}}',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'market-items',
        type: 'text',
        x: 80,
        y: 290,
        width: 520,
        height: 140,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'item_list',
        placeholderText: '{{item_list}}',
        props: {
          text: '1 x Apples..........................$3.00\n2 x Bread...........................$4.50\n1 x Coffee..........................$2.50',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.4,
        },
      },
      {
        id: 'market-total-label',
        type: 'text',
        x: 80,
        y: 450,
        width: 320,
        height: 34,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'TOTAL',
          fontSize: 18,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'market-total-value',
        type: 'price',
        x: 420,
        y: 450,
        width: 220,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'total',
        placeholderText: '{{total}}',
        props: {
          value: '0.00',
          currency: '$',
          fontSize: 26,
          fontWeight: 700,
          color: '#000000',
        },
      },
      {
        id: 'market-footer',
        type: 'text',
        x: 80,
        y: 520,
        width: 520,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'THANK YOU FOR SHOPPING WITH US',
          fontSize: 14,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
    ],
  },
  {
    id: 'cinema-stub',
    title: 'Cinema Stub',
    thumbnail_placeholder: 'Cinema Stub',
    background: '#ffffff',
    elements: [
      {
        id: 'cinema-title',
        type: 'text',
        x: 80,
        y: 40,
        width: 520,
        height: 54,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'WEST END CINEMA',
          fontSize: 36,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.1,
        },
      },
      {
        id: 'cinema-head',
        type: 'text',
        x: 80,
        y: 100,
        width: 520,
        height: 38,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Ticket stub / concession receipt',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 500,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'cinema-divider',
        type: 'line',
        x: 80,
        y: 150,
        width: 520,
        height: 2,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          stroke: '#000000',
          strokeWidth: 2,
          strokeStyle: 'dashed',
        },
      },
      {
        id: 'cinema-film',
        type: 'text',
        x: 80,
        y: 170,
        width: 520,
        height: 48,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'custom_field',
        placeholderText: '{{film_title}}',
        props: {
          text: 'Film: {{film_title}}',
          fontSize: 18,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 500,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'cinema-showtime',
        type: 'text',
        x: 80,
        y: 225,
        width: 520,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'transaction_date',
        placeholderText: '{{transaction_date}}',
        props: {
          text: 'Showtime: {{transaction_date}}',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'cinema-seats',
        type: 'text',
        x: 80,
        y: 280,
        width: 520,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Row A / Seat 14  |  Adult',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'cinema-price',
        type: 'price',
        x: 80,
        y: 340,
        width: 260,
        height: 38,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'total',
        placeholderText: '{{total}}',
        props: {
          value: '12.00',
          currency: '$',
          fontSize: 24,
          fontWeight: 700,
          color: '#000000',
        },
      },
      {
        id: 'cinema-barcode',
        type: 'barcode',
        x: 80,
        y: 400,
        width: 520,
        height: 86,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          format: 'CODE128',
          value: 'CINEMA2026',
          color: '#000000',
        },
      },
    ],
  },
  {
    id: 'minimal-grocery',
    title: 'Minimal Grocery',
    thumbnail_placeholder: 'Minimal Grocery',
    background: '#ffffff',
    elements: [
      {
        id: 'grocery-header',
        type: 'text',
        x: 80,
        y: 40,
        width: 560,
        height: 50,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'BARN & BASKET',
          fontSize: 34,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.1,
        },
      },
      {
        id: 'grocery-address',
        type: 'text',
        x: 80,
        y: 100,
        width: 520,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'customer_address',
        placeholderText: '{{customer_address}}',
        props: {
          text: 'Address: {{customer_address}}',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'grocery-divider',
        type: 'line',
        x: 80,
        y: 150,
        width: 560,
        height: 2,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          stroke: '#000000',
          strokeWidth: 2,
          strokeStyle: 'solid',
        },
      },
      {
        id: 'grocery-items',
        type: 'text',
        x: 80,
        y: 180,
        width: 520,
        height: 140,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'item_list',
        placeholderText: '{{item_list}}',
        props: {
          text: 'Eggs x1...........................$2.75\nMilk x1...........................$1.95\nBread x1..........................$1.80',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.4,
        },
      },
      {
        id: 'grocery-subtotal',
        type: 'text',
        x: 80,
        y: 340,
        width: 260,
        height: 34,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'subtotal',
        placeholderText: '{{subtotal}}',
        props: {
          text: 'SUBTOTAL: $0.00',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 500,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'grocery-total',
        type: 'price',
        x: 80,
        y: 390,
        width: 220,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'total',
        placeholderText: '{{total}}',
        props: {
          value: '6.50',
          currency: '$',
          fontSize: 24,
          fontWeight: 700,
          color: '#000000',
        },
      },
      {
        id: 'grocery-line',
        type: 'line',
        x: 80,
        y: 450,
        width: 560,
        height: 2,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          stroke: '#000000',
          strokeWidth: 2,
          strokeStyle: 'solid',
        },
      },
      {
        id: 'grocery-footer',
        type: 'text',
        x: 80,
        y: 470,
        width: 520,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'SAVINGS WITH EVERY SHOP',
          fontSize: 14,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#333333',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
    ],
  },
  {
    id: 'coffee-house',
    title: 'Coffee House Receipt',
    thumbnail_placeholder: 'Coffee House',
    background: '#ffffff',
    elements: [
      {
        id: 'coffee-brand',
        type: 'text',
        x: 80,
        y: 40,
        width: 560,
        height: 52,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'THE DAILY GRIND',
          fontSize: 36,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#2b2b2b',
          textAlign: 'left',
          lineHeight: 1.1,
        },
      },
      {
        id: 'coffee-tagline',
        type: 'text',
        x: 80,
        y: 100,
        width: 520,
        height: 28,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Fresh brews. Toasty bites. Good vibes.',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#5f5f5f',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'coffee-divider',
        type: 'line',
        x: 80,
        y: 140,
        width: 560,
        height: 2,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          stroke: '#d9d9d9',
          strokeWidth: 2,
          strokeStyle: 'solid',
        },
      },
      {
        id: 'coffee-customer',
        type: 'text',
        x: 80,
        y: 160,
        width: 520,
        height: 36,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'customer_name',
        placeholderText: '{{customer_name}}',
        props: {
          text: 'Customer: {{customer_name}}',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 500,
          color: '#2b2b2b',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'coffee-date',
        type: 'text',
        x: 80,
        y: 205,
        width: 520,
        height: 32,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'transaction_date',
        placeholderText: '{{transaction_date}}',
        props: {
          text: 'Date: {{transaction_date}}',
          fontSize: 15,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#4a4a4a',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
      {
        id: 'coffee-items',
        type: 'text',
        x: 80,
        y: 250,
        width: 520,
        height: 150,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'item_list',
        placeholderText: '{{item_list}}',
        props: {
          text: '1 x Latte............................$4.50\n2 x Almond Croissant..............$6.00\n1 x Cold Brew.......................$3.75',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#2b2b2b',
          textAlign: 'left',
          lineHeight: 1.5,
        },
      },
      {
        id: 'coffee-total-label',
        type: 'text',
        x: 80,
        y: 420,
        width: 260,
        height: 30,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Grand Total',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 600,
          color: '#000000',
          textAlign: 'left',
          lineHeight: 1.2,
        },
      },
      {
        id: 'coffee-total-value',
        type: 'price',
        x: 380,
        y: 415,
        width: 220,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'total',
        placeholderText: '{{total}}',
        props: {
          value: '14.25',
          currency: '$',
          fontSize: 26,
          fontWeight: 700,
          color: '#000000',
        },
      },
      {
        id: 'coffee-footer',
        type: 'text',
        x: 80,
        y: 480,
        width: 520,
        height: 36,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'See you again for your next cup!',
          fontSize: 14,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#5f5f5f',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
    ],
  },
  {
    id: 'boutique-bakery',
    title: 'Boutique Bakery',
    thumbnail_placeholder: 'Boutique Bakery',
    background: '#ffffff',
    elements: [
      {
        id: 'bakery-name',
        type: 'text',
        x: 80,
        y: 40,
        width: 560,
        height: 52,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'BLOOM & BAKE',
          fontSize: 34,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#1f1f1f',
          textAlign: 'left',
          lineHeight: 1.1,
        },
      },
      {
        id: 'bakery-subtitle',
        type: 'text',
        x: 80,
        y: 100,
        width: 520,
        height: 28,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Artisan pastries & sweet celebrations',
          fontSize: 14,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#555555',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
      {
        id: 'bakery-customer',
        type: 'text',
        x: 80,
        y: 140,
        width: 520,
        height: 34,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'customer_name',
        placeholderText: '{{customer_name}}',
        props: {
          text: 'Customer: {{customer_name}}',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 500,
          color: '#1f1f1f',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
      {
        id: 'bakery-date',
        type: 'text',
        x: 80,
        y: 186,
        width: 520,
        height: 32,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'transaction_date',
        placeholderText: '{{transaction_date}}',
        props: {
          text: 'Date: {{transaction_date}}',
          fontSize: 15,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#555555',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
      {
        id: 'bakery-items',
        type: 'text',
        x: 80,
        y: 230,
        width: 520,
        height: 150,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'item_list',
        placeholderText: '{{item_list}}',
        props: {
          text: '1 x Croissant......................$3.20\n1 x Lemon Tart......................$4.75\n1 x Espresso........................$2.80',
          fontSize: 16,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#1f1f1f',
          textAlign: 'left',
          lineHeight: 1.5,
        },
      },
      {
        id: 'bakery-total',
        type: 'price',
        x: 80,
        y: 400,
        width: 220,
        height: 40,
        rotation: 0,
        zIndex: 1,
        isDynamic: true,
        formFieldType: 'total',
        placeholderText: '{{total}}',
        props: {
          value: '10.75',
          currency: '$',
          fontSize: 24,
          fontWeight: 700,
          color: '#1f1f1f',
        },
      },
      {
        id: 'bakery-note',
        type: 'text',
        x: 80,
        y: 460,
        width: 520,
        height: 36,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'Made with handcrafted care.',
          fontSize: 14,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 400,
          color: '#5f5f5f',
          textAlign: 'left',
          lineHeight: 1.3,
        },
      },
    ],
  },
];
