export const TEMPLATES = [
  {
    id: 'default-receipt',
    title: 'Default Receipt Template',
    thumbnail_placeholder: 'Default Receipt',
    width: 400,
    height: 800,
    background: '#ffffff',
    elements: [
      {
        id: 'default-logo',
        type: 'image',
        x: 144,
        y: 30,
        width: 112,
        height: 58,
        rotation: 0,
        zIndex: 1,
        isDynamic: false,
        formFieldType: null,
        props: {
          src: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="112" height="58" viewBox="0 0 112 58"><g fill="black"><rect x="0" y="24" width="8" height="10"/><rect x="13" y="14" width="8" height="30"/><rect x="26" y="5" width="8" height="48"/><rect x="39" y="0" width="8" height="58"/><rect x="52" y="14" width="8" height="30"/><rect x="65" y="0" width="8" height="58"/><rect x="78" y="5" width="8" height="48"/><rect x="91" y="14" width="8" height="30"/><rect x="104" y="24" width="8" height="10"/></g></svg>',
          fit: 'contain',
        },
      },
      {
        id: 'store-name',
        type: 'text',
        x: 20,
        y: 115,
        width: 360,
        height: 35,
        rotation: 0,
        zIndex: 2,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'YOUR STORE NAME',
          fontSize: 26,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 900,
          color: '#000000',
          textAlign: 'center',
          lineHeight: 1.1,
        },
      },
      {
        id: 'store-desc',
        type: 'text',
        x: 20,
        y: 150,
        width: 360,
        height: 20,
        rotation: 0,
        zIndex: 3,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'YOUR DESCRIPTION',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'center',
          lineHeight: 1.2,
        },
      },
      {
        id: 'divider-1',
        type: 'text',
        x: 20,
        y: 180,
        width: 360,
        height: 15,
        rotation: 0,
        zIndex: 4,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: '----------------------------------------',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          color: '#000000',
          textAlign: 'center',
        },
      },
      {
        id: 'lbl-customer',
        type: 'text',
        x: 30,
        y: 205,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 5,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'CUSTOMER',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-customer',
        type: 'text',
        x: 180,
        y: 205,
        width: 190,
        height: 20,
        rotation: 0,
        zIndex: 6,
        isDynamic: true,
        formFieldType: 'customer_name',
        placeholderText: '{{customer_name}}',
        props: {
          text: 'CUSTOMER NAME',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'lbl-address',
        type: 'text',
        x: 30,
        y: 230,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 7,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'ADDRESS',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-address',
        type: 'text',
        x: 140,
        y: 230,
        width: 230,
        height: 20,
        rotation: 0,
        zIndex: 8,
        isDynamic: true,
        formFieldType: 'customer_address',
        placeholderText: '{{customer_address}}',
        props: {
          text: 'INSERT CUSTOMER ADDRESS HERE',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'lbl-date',
        type: 'text',
        x: 30,
        y: 255,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 9,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'DATE',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-date',
        type: 'text',
        x: 180,
        y: 255,
        width: 190,
        height: 20,
        rotation: 0,
        zIndex: 10,
        isDynamic: true,
        formFieldType: 'date',
        placeholderText: '{{date}}',
        props: {
          text: '2026-05-27',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'divider-2',
        type: 'text',
        x: 20,
        y: 285,
        width: 360,
        height: 15,
        rotation: 0,
        zIndex: 11,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: '----------------------------------------',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          color: '#000000',
          textAlign: 'center',
        },
      },
      {
        id: 'items-table',
        type: 'table',
        x: 30,
        y: 310,
        width: 340,
        height: 110,
        rotation: 0,
        zIndex: 12,
        isDynamic: true,
        formFieldType: 'line_items',
        placeholderText: '{{line_items}}',
        props: {
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          color: '#000000',
          lineHeight: 1.4,
          columns: [
            { key: 'no', label: 'NO', width: 10, textAlign: 'left' },
            { key: 'desc', label: 'ITEM', width: 50, textAlign: 'left' },
            { key: 'qty', label: 'QTY', width: 20, textAlign: 'right' },
            { key: 'price', label: 'AMT', width: 20, textAlign: 'right' }
          ]
        },
      },
      {
        id: 'divider-3',
        type: 'text',
        x: 20,
        y: 430,
        width: 360,
        height: 15,
        rotation: 0,
        zIndex: 13,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: '----------------------------------------',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          color: '#000000',
          textAlign: 'center',
        },
      },
      {
        id: 'lbl-total-qty',
        type: 'text',
        x: 30,
        y: 455,
        width: 150,
        height: 20,
        rotation: 0,
        zIndex: 14,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'TOTAL ITEMS',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-total-qty',
        type: 'text',
        x: 200,
        y: 455,
        width: 170,
        height: 20,
        rotation: 0,
        zIndex: 15,
        isDynamic: true,
        formFieldType: 'total_qty',
        placeholderText: '{{total_qty}}',
        props: {
          text: '03',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'lbl-grand-total',
        type: 'text',
        x: 30,
        y: 480,
        width: 150,
        height: 20,
        rotation: 0,
        zIndex: 16,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'GRAND TOTAL',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-grand-total',
        type: 'text',
        x: 200,
        y: 480,
        width: 170,
        height: 20,
        rotation: 0,
        zIndex: 17,
        isDynamic: true,
        formFieldType: 'total_amount',
        placeholderText: '{{total_amount}}',
        props: {
          text: '$0.00',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'divider-4',
        type: 'text',
        x: 20,
        y: 515,
        width: 360,
        height: 15,
        rotation: 0,
        zIndex: 18,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: '----------------------------------------',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          color: '#000000',
          textAlign: 'center',
        },
      },
      {
        id: 'lbl-remark',
        type: 'text',
        x: 30,
        y: 540,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 19,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'REMARK',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-remark',
        type: 'text',
        x: 130,
        y: 540,
        width: 240,
        height: 20,
        rotation: 0,
        zIndex: 20,
        isDynamic: true,
        formFieldType: 'remark',
        placeholderText: '{{remark}}',
        props: {
          text: '-',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'lbl-payment',
        type: 'text',
        x: 30,
        y: 565,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 21,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'PAYMENT',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-payment',
        type: 'text',
        x: 130,
        y: 565,
        width: 240,
        height: 20,
        rotation: 0,
        zIndex: 22,
        isDynamic: true,
        formFieldType: 'payment_method',
        placeholderText: '{{payment_method}}',
        props: {
          text: 'PAYMENT METHOD',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'lbl-auth',
        type: 'text',
        x: 30,
        y: 590,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 23,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'AUTH',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'left',
        },
      },
      {
        id: 'val-auth',
        type: 'text',
        x: 130,
        y: 590,
        width: 240,
        height: 20,
        rotation: 0,
        zIndex: 24,
        isDynamic: true,
        formFieldType: 'auth_code',
        placeholderText: '{{auth_code}}',
        props: {
          text: 'AM-0926',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'right',
        },
      },
      {
        id: 'divider-5',
        type: 'text',
        x: 20,
        y: 615,
        width: 360,
        height: 15,
        rotation: 0,
        zIndex: 25,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: '----------------------------------------',
          fontSize: 13,
          fontFamily: 'JetBrains Mono, monospace',
          color: '#000000',
          textAlign: 'center',
        },
      },
      {
        id: 'thank-you-msg',
        type: 'text',
        x: 20,
        y: 640,
        width: 360,
        height: 20,
        rotation: 0,
        zIndex: 26,
        isDynamic: false,
        formFieldType: null,
        props: {
          text: 'THANK YOU / COME BACK SOON',
          fontSize: 13,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 700,
          color: '#000000',
          textAlign: 'center',
        },
      },
      {
        id: 'barcode',
        type: 'barcode',
        x: 70,
        y: 675,
        width: 260,
        height: 70,
        rotation: 0,
        zIndex: 27,
        isDynamic: false,
        formFieldType: null,
        props: {
          format: 'CODE128',
          value: 'DEFAULT1234',
        },
      },
    ],
  },
];
